							<!-- Button trigger modal -->
							<button type="button" id="addTaskBtn" class="btn btn-success btn-add-float radius-30 p-1 invisible" data-bs-toggle="modal" data-bs-target="#addTaskModal">
								<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus">
									<line x1="15" y1="5" x2="15" y2="25"></line>
									<line x1="5" y1="15" x2="25" y2="15"></line>
								</svg>
							</button>
							<div class="modal fade" id="addTaskModal" tabindex="-1" style="display: none;" aria-hidden="true">
								<div class="modal-dialog modal-xl">
									<div class="modal-content p-3">
										<form id="addTaskFormElement" action="" method="post" autocomplete="off">
											<div class="modal-header">
												<h5 class="modal-title">Add task to <?= $data['page_title'] ?></h5>
												<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
											</div>
											<div class="modal-body" id="addTaskForm">
												<div class="container-fluid">
													<div class="row row-cols-1 row-cols-lg-2">
														<div class="col-12">
															<div class="col-sm-12 pb-3">
																<label for="taskTitle" class="form-label">Title</label>
																<input type="text" name="title" class="form-control" id="addTaskTitle" placeholder="Title">
															</div>
															<div class="col-sm-12 pb-3">
																<label for="taskDescription" class="form-label">Description</label>
																<textarea name="description" class="form-control" id="addTaskDescription" placeholder="Description..." rows="6"></textarea>
															</div>
															<div class="col-sm-12 pb-3">
																<label for="taskPriority" class="form-label">Priority</label>
																<div class="dropdown hierarchy-select" id="addTaskPriority">
																	<button type="button" class="btn btn-outline-secondary text-start dropdown-toggle" id="select-priority-button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
																	<div class="dropdown-menu" aria-labelledby="select-priority-button">
																		<div class="hs-searchbox">
																			<input type="text" class="form-control" autocomplete="off">
																		</div>
																		<div class="hs-menu-inner">
																			<a class="dropdown-item" data-value="0" data-default-selected="" href="#"><span class="ps-2"> No priority</span></a>
																			<a class="dropdown-item" data-value="1" href="#"><i class="fas fa-flag fa-sm text-muted"></i><span class="ps-2"> Low</span></a>
																			<a class="dropdown-item" data-value="2" href="#"><i class="fas fa-flag fa-sm text-info"></i><span class="ps-2"> Normal</span></a>
																			<a class="dropdown-item" data-value="3" href="#"><i class="fas fa-flag fa-sm text-warning"></i><span class="ps-2"> High</span></a>
																			<a class="dropdown-item" data-value="4" href="#"><i class="fas fa-flag fa-sm text-danger"></i><span class="ps-2"> Urgent</span></a>
																		</div>
																	</div>
																	<input class="d-none" name="priority" readonly="readonly" aria-hidden="true" type="text" value="" />
																</div>
															</div>
														</div>
														<div class="col-12 ps-lg-5">
															<div class="modal-section-label">
																Date/time options
															</div>
															<div class="row row-cols-1 row-cols-xl-2">
																<div class="col-12">
																	<label class="form-label">Start</label>
																	<div class="row row-cols-2 g-1">
																		<div class="date-container">
																			<input class="result form-control" type="text" id="addTaskStartDate" name="taskStartDate" placeholder="Date">
																		</div>
																		<div class="time-container">
																			<input class="result form-control" type="text" id="addTaskStartTime" name="taskStartTime" placeholder="Time">
																		</div>
																	</div>
																</div>
																<div class="col-12">
																	<label class="form-label">Due</label>
																	<div class="row row-cols-2 g-1">
																		<div class="date-container">
																			<input class="result form-control" type="text" id="addTaskDueDate" name="taskDueDate" placeholder="Date">
																		</div>
																		<div class="time-container">
																			<input class="result form-control" type="text" id="addTaskDueTime" name="taskDueTime" placeholder="Time">
																		</div>
																	</div>
																</div>
															</div>
															<div class="row">
																<div class="col-12">
																	<div class="form-check form-switch pt-2">
																		<input name="allDayTask" class="form-check-input" type="checkbox" id="addAllDayTask">
																		<label class="form-check-label" for="addAllDayTask">All Day</label>
																	</div>
																</div>
															</div>
															<div class="row">
																<div class="col-12 pt-2">
																	<label class="form-label">Time zone</label>
																	<select class="form-control form-select-sm" name="timezone" id="timezone">
																		<option value="" selected disabled>Please select time zone</option>
																		<option value="Pacific/Midway">(GMT-11:00) Midway Island, Samoa</option>
																		<option value="America/Adak">(GMT-10:00) Hawaii-Aleutian</option>
																		<option value="Etc/GMT+10">(GMT-10:00) Hawaii</option>
																		<option value="Pacific/Marquesas">(GMT-09:30) Marquesas Islands</option>
																		<option value="Pacific/Gambier">(GMT-09:00) Gambier Islands</option>
																		<option value="America/Anchorage">(GMT-09:00) Alaska</option>
																		<option value="America/Ensenada">(GMT-08:00) Tijuana, Baja California</option>
																		<option value="Etc/GMT+8">(GMT-08:00) Pitcairn Islands</option>
																		<option value="America/Los_Angeles">(GMT-08:00) Pacific Time (US & Canada)</option>
																		<option value="America/Denver">(GMT-07:00) Mountain Time (US & Canada)</option>
																		<option value="America/Chihuahua">(GMT-07:00) Chihuahua, La Paz, Mazatlan</option>
																		<option value="America/Dawson_Creek">(GMT-07:00) Arizona</option>
																		<option value="America/Belize">(GMT-06:00) Saskatchewan, Central America</option>
																		<option value="America/Cancun">(GMT-06:00) Guadalajara, Mexico City, Monterrey</option>
																		<option value="Chile/EasterIsland">(GMT-06:00) Easter Island</option>
																		<option value="America/Chicago">(GMT-06:00) Central Time (US & Canada)</option>
																		<option value="America/New_York">(GMT-05:00) Eastern Time (US & Canada)</option>
																		<option value="America/Havana">(GMT-05:00) Cuba</option>
																		<option value="America/Bogota">(GMT-05:00) Bogota, Lima, Quito, Rio Branco</option>
																		<option value="America/Caracas">(GMT-04:30) Caracas</option>
																		<option value="America/Santiago">(GMT-04:00) Santiago</option>
																		<option value="America/La_Paz">(GMT-04:00) La Paz</option>
																		<option value="Atlantic/Stanley">(GMT-04:00) Faukland Islands</option>
																		<option value="America/Campo_Grande">(GMT-04:00) Brazil</option>
																		<option value="America/Goose_Bay">(GMT-04:00) Atlantic Time (Goose Bay)</option>
																		<option value="America/Glace_Bay">(GMT-04:00) Atlantic Time (Canada)</option>
																		<option value="America/St_Johns">(GMT-03:30) Newfoundland</option>
																		<option value="America/Araguaina">(GMT-03:00) UTC-3</option>
																		<option value="America/Montevideo">(GMT-03:00) Montevideo</option>
																		<option value="America/Miquelon">(GMT-03:00) Miquelon, St. Pierre</option>
																		<option value="America/Godthab">(GMT-03:00) Greenland</option>
																		<option value="America/Argentina/Buenos_Aires">(GMT-03:00) Buenos Aires</option>
																		<option value="America/Sao_Paulo">(GMT-03:00) Brasilia</option>
																		<option value="America/Noronha">(GMT-02:00) Mid-Atlantic</option>
																		<option value="Atlantic/Cape_Verde">(GMT-01:00) Cape Verde Is.</option>
																		<option value="Atlantic/Azores">(GMT-01:00) Azores</option>
																		<option value="Europe/Belfast">(GMT) Greenwich Mean Time : Belfast</option>
																		<option value="Europe/Dublin">(GMT) Greenwich Mean Time : Dublin</option>
																		<option value="Europe/Lisbon">(GMT) Greenwich Mean Time : Lisbon</option>
																		<option value="Europe/London">(GMT) Greenwich Mean Time : London</option>
																		<option value="Africa/Abidjan">(GMT) Monrovia, Reykjavik</option>
																		<option value="Europe/Amsterdam">(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna</option>
																		<option value="Europe/Belgrade">(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague</option>
																		<option value="Europe/Brussels">(GMT+01:00) Brussels, Copenhagen, Madrid, Paris</option>
																		<option value="Africa/Algiers">(GMT+01:00) West Central Africa</option>
																		<option value="Africa/Windhoek">(GMT+01:00) Windhoek</option>
																		<option value="Asia/Beirut">(GMT+02:00) Beirut</option>
																		<option value="Africa/Cairo">(GMT+02:00) Cairo</option>
																		<option value="Asia/Gaza">(GMT+02:00) Gaza</option>
																		<option value="Africa/Blantyre">(GMT+02:00) Harare, Pretoria</option>
																		<option value="Asia/Jerusalem">(GMT+02:00) Jerusalem</option>
																		<option value="Europe/Minsk">(GMT+02:00) Minsk</option>
																		<option value="Asia/Damascus">(GMT+02:00) Syria</option>
																		<option value="Europe/Moscow">(GMT+03:00) Moscow, St. Petersburg, Volgograd</option>
																		<option value="Africa/Addis_Ababa">(GMT+03:00) Nairobi</option>
																		<option value="Asia/Tehran">(GMT+03:30) Tehran</option>
																		<option value="Asia/Dubai">(GMT+04:00) Abu Dhabi, Muscat</option>
																		<option value="Asia/Yerevan">(GMT+04:00) Yerevan</option>
																		<option value="Asia/Kabul">(GMT+04:30) Kabul</option>
																		<option value="Asia/Yekaterinburg">(GMT+05:00) Ekaterinburg</option>
																		<option value="Asia/Tashkent">(GMT+05:00) Tashkent</option>
																		<option value="Asia/Kolkata">(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi</option>
																		<option value="Asia/Katmandu">(GMT+05:45) Kathmandu</option>
																		<option value="Asia/Dhaka">(GMT+06:00) Astana, Dhaka</option>
																		<option value="Asia/Novosibirsk">(GMT+06:00) Novosibirsk</option>
																		<option value="Asia/Rangoon">(GMT+06:30) Yangon (Rangoon)</option>
																		<option value="Asia/Bangkok">(GMT+07:00) Bangkok, Hanoi, Jakarta</option>
																		<option value="Asia/Krasnoyarsk">(GMT+07:00) Krasnoyarsk</option>
																		<option value="Asia/Hong_Kong">(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi</option>
																		<option value="Asia/Irkutsk">(GMT+08:00) Irkutsk, Ulaan Bataar</option>
																		<option value="Australia/Perth">(GMT+08:00) Perth</option>
																		<option value="Australia/Eucla">(GMT+08:45) Eucla</option>
																		<option value="Asia/Tokyo">(GMT+09:00) Osaka, Sapporo, Tokyo</option>
																		<option value="Asia/Seoul">(GMT+09:00) Seoul</option>
																		<option value="Asia/Yakutsk">(GMT+09:00) Yakutsk</option>
																		<option value="Australia/Adelaide">(GMT+09:30) Adelaide</option>
																		<option value="Australia/Darwin">(GMT+09:30) Darwin</option>
																		<option value="Australia/Brisbane">(GMT+10:00) Brisbane</option>
																		<option value="Australia/Hobart">(GMT+10:00) Hobart</option>
																		<option value="Asia/Vladivostok">(GMT+10:00) Vladivostok</option>
																		<option value="Australia/Lord_Howe">(GMT+10:30) Lord Howe Island</option>
																		<option value="Etc/GMT-11">(GMT+11:00) Solomon Is., New Caledonia</option>
																		<option value="Asia/Magadan">(GMT+11:00) Magadan</option>
																		<option value="Pacific/Norfolk">(GMT+11:30) Norfolk Island</option>
																		<option value="Asia/Anadyr">(GMT+12:00) Anadyr, Kamchatka</option>
																		<option value="Pacific/Auckland">(GMT+12:00) Auckland, Wellington</option>
																		<option value="Etc/GMT-12">(GMT+12:00) Fiji, Kamchatka, Marshall Is.</option>
																		<option value="Pacific/Chatham">(GMT+12:45) Chatham Islands</option>
																		<option value="Pacific/Tongatapu">(GMT+13:00) Nuku'alofa</option>
																		<option value="Pacific/Kiritimati">(GMT+14:00) Kiritimati</option>
																	</select>
																</div>
															</div>


															<div class="row pt-4">
																<div class="col-12">
																	<div class="form-check form-switch">
																		<input name="repeatTask" class="form-check-input" type="checkbox" id="addRepeatTask" data-bs-toggle="collapse" data-bs-target="#addRepeatTaskOptions" aria-expanded="true">
																		<label class="form-check-label" for="addRepeatTask">Repeat task</label>
																	</div>
																</div>
																<div class="col-sm-12 pt-2 collapse" id="addRepeatTaskOptions">
																	<div class="modal-section-label pb-2">Repeat options</div>
																	<div class="row g-1 py-0" id="rrule">
																		<div class="col-auto" id="rrule-freq">
																			<select class="form-control form-select-sm frequency">
																				<option value="YEARLY">Yearly</option>
																				<option value="MONTHLY">Monthly</option>
																				<option value="WEEKLY">Weekly</option>
																				<option value="DAILY">Daily</option>
																			</select>
																		</div>
																		<div class="row g-1 yearly">
																			<div class="col-auto">
																				<select class="form-control form-select-sm type">
																					<option value="on">By Date in Month</option>
																					<option value="onthe">By nth Day(s) in Month(s)</option>
																				</select>
																			</div>
																			<div class="col-auto">
																				<div class="row g-1 yearly-on" data-selector="yearly-on">
																					<div class="col-auto">
																						<select class="form-control form-select-sm month">
																							<option value="1">January</option>
																							<option value="2">February</option>
																							<option value="3">March</option>
																							<option value="4">April</option>
																							<option value="5">May</option>
																							<option value="6">June</option>
																							<option value="7">July</option>
																							<option value="8">August</option>
																							<option value="9">September</option>
																							<option value="10">October</option>
																							<option value="11">November</option>
																							<option value="12">December</option>
																						</select>
																					</div>
																					<div class="col-auto">
																						<select class="form-control form-select-sm monthday">
																						</select>
																					</div>
																					</span>
																				</div>
																			</div>
																			<div class="col-auto yearly-onthe" data-selector="yearly-onthe">
																				<select class="nth" id="select-nth" multiple>
																					<option value="1">1st</option>
																					<option value="2">2nd</option>
																					<option value="3">3rd</option>
																					<option value="4">4th</option>
																					<option value="-1">Last</option>
																				</select>
																				<select class="day" id="select-day" multiple>
																					<option value="MO">Monday</option>
																					<option value="TU">Tuesday</option>
																					<option value="WE">Wednesday</option>
																					<option value="TH">Thursday</option>
																					<option value="FR">Friday</option>
																					<option value="SA">Saturday</option>
																					<option value="SU">Sunday</option>
																				</select>
																				<span class="align-self-center pe-1"> of </span>
																				<select class="form-control form-select-sm pe-2 month" id="select-month" multiple>
																					<option value="1">January</option>
																					<option value="2">February</option>
																					<option value="3">March</option>
																					<option value="4">April</option>
																					<option value="5">May</option>
																					<option value="6">June</option>
																					<option value="7">July</option>
																					<option value="8">August</option>
																					<option value="9">September</option>
																					<option value="10">October</option>
																					<option value="11">November</option>
																					<option value="12">December</option>
																				</select>
																			</div>
																		</div>
																		<div class="row g-1 py-0 monthly">
																			<div class="col-auto py-0">
																				Every <input type="number" class="interval" value="1" /> month(s)
																			</div>
																			<div class="row g-1 py-0">
																				<div class="col-auto">
																					<select class="form-control form-select-sm type">
																						<option value="on">By Date in Month</option>
																						<option value="onthe">By nth Day(s) in Month(s)</option>
																					</select>
																				</div>
																				<div class="col-auto">
																					<div class="row g-0 monthly-on" data-selector="monthly-on">
																						<select class="form-control form-select-sm monthday">
																							<option value="1">1</option>
																							<option value="2">2</option>
																							<option value="3">3</option>
																							<option value="4">4</option>
																							<option value="5">5</option>
																							<option value="6">6</option>
																							<option value="7">7</option>
																							<option value="8">8</option>
																							<option value="9">9</option>
																							<option value="10">10</option>
																							<option value="11">11</option>
																							<option value="12">12</option>
																							<option value="13">13</option>
																							<option value="14">14</option>
																							<option value="15">15</option>
																							<option value="16">16</option>
																							<option value="17">17</option>
																							<option value="18">18</option>
																							<option value="19">19</option>
																							<option value="20">20</option>
																							<option value="21">21</option>
																							<option value="22">22</option>
																							<option value="23">23</option>
																							<option value="24">24</option>
																							<option value="25">25</option>
																							<option value="26">26</option>
																							<option value="27">27</option>
																							<option value="28">28</option>
																							<option value="29">29</option>
																							<option value="30">30</option>
																							<option value="31">31</option>
																						</select>
																					</div>
																				</div>
																				<div class="col-auto monthly-onthe" data-selector="monthly-onthe">
																					<select class="nth" id="select-nth" multiple>
																						<option value="1">1st</option>
																						<option value="2">2nd</option>
																						<option value="3">3rd</option>
																						<option value="4">4th</option>
																						<option value="-1">Last</option>
																					</select>
																					<select class="day" id="select-day" multiple>
																						<option value="MO">Monday</option>
																						<option value="TU">Tuesday</option>
																						<option value="WE">Wednesday</option>
																						<option value="TH">Thursday</option>
																						<option value="FR">Friday</option>
																						<option value="SA">Saturday</option>
																						<option value="SU">Sunday</option>
																					</select>
																				</div>
																			</div>
																		</div>
																		<div class="row g-1 py-0 weekly" data-selector="weekly">
																			<div class="col-auto py-0">
																				Every <input type="number" class="interval" value="1" /> week(s) on
																				<select class="day" id="select-days" multiple>
																					<option value="MO">Monday</option>
																					<option value="TU">Tuesday</option>
																					<option value="WE">Wednesday</option>
																					<option value="TH">Thursday</option>
																					<option value="FR">Friday</option>
																					<option value="SA">Saturday</option>
																					<option value="SU">Sunday</option>
																				</select>
																			</div>
																		</div>
																		<div class="row g-1 py-0 daily" data-selector="daily">
																			<div class="col-auto py-0">
																				Every <input type="number" class="interval" value="1" /> day(s)
																			</div>
																		</div>
																		<div class="row g-1 pt-2" id="rrules-end">
																			<div class="col-auto mb-0">
																				<select class="form-control form-select-sm ends">
																					<option value="never">Never Ends</option>
																					<option value="count">Ends After</option>
																					<option value="until">Ends on Date</option>
																				</select>
																			</div>
																			<div class="col-auto align-items-center py-0 ends-at count">
																				<input type="number" class="me-1 interval" value="1" /> instance(s)
																			</div>
																			<div class="col-auto py-0 ends-at until">
																				<input class="date form-control form-select-sm w-50" type="text" id="#addRepeatTaskDueDate" />
																			</div>
																			<div class="row g-1" id="result">
																				<div class="modal-section-label">Repeat options preview</div>
																				<div class="row" id="rrule-result"></div>
																				<div class="col" id="calendar1"></div>
																				<div class="col" id="calendar2"></div>
																				<div class="col" id="calendar3"></div>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class="row pt-3">
																<div class="col-sm-4">
																	<div class="form-check form-switch">
																		<input name="taskReminder" class="form-check-input" type="checkbox" id="addTaskReminder" data-bs-toggle="collapse" data-bs-target="#addTaskReminderOptions" aria-expanded="true">
																		<label class="form-check-label" for="taskReminder">Task reminder</label>
																	</div>
																</div>
																<div class="col collapse" id="addTaskReminderOptions">
																	<div class="modal-section-label pb-2">Reminder options</div>

																</div>
															</div>
															<div class="col-sm-12">
																<div class="d-grid">
																	<input type="hidden" name="token" value="<?= isset($_SESSION['token']) ? $_SESSION['token'] : '' ?>" />
																	<input type="hidden" name="space_id" value="<?= isset($_SESSION['space_ids']) ? $_SESSION['space_ids'][0] : '' ?>" />
																	<input type="hidden" name="owner_id" value="<?= isset($_SESSION['user_id']) ? $_SESSION['user_id'] : '' ?>" />
																	<input type="hidden" name="rrule-data" id="rrule-data" value="" />
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="modal-footer">
												<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
												<button type="submit" class="btn btn-primary order-last" id="add-task">Add task</button>
											</div>
										</form>
									</div>
								</div>
							</div>