<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--favicon
	<link rel="icon" href="<?= ASSETS ?>images/favicon-32x32.png" type="image/png" />-->
	<!--plugins-->
	<link href="<?= ASSETS ?>plugins/simplebar/css/simplebar.css" rel="stylesheet" />
	<link href="<?= ASSETS ?>plugins/fullcalendar/css/main.min.css" rel="stylesheet" />
	<link href="<?= ASSETS ?>plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.min.css" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
	<link href="<?= ASSETS ?>plugins/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet" />
	<link href="<?= ASSETS ?>plugins/metismenu/css/metisMenu.min.css" rel="stylesheet" />
	<link href="https://use.fontawesome.com/releases/v6.2.0/css/all.css" rel="stylesheet">
	<link href="<?= ASSETS ?>plugins/fontawesome-iconpicker/dist/css/fontawesome-iconpicker.min.css" rel="stylesheet" />
	<link href="<?= ASSETS ?>plugins/hierarchy-select-2/css/hierarchy-select.min.css" rel="stylesheet" />
	<link href="<?= ASSETS ?>plugins/bootstrap-multiselect/dist/css/bootstrap-multiselect.min.css" rel="stylesheet" />
	<link href="<?= ASSETS ?>plugins/notifications/css/lobibox.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/css/bootstrap-select.min.css" integrity="sha512-mR/b5Y7FRsKqrYZou7uysnOdCIJib/7r5QeJMFvLNHNhtye3xJp1TdJVPLtetkukFn227nKpXD9OjUc09lx97Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<!-- loader-->
	<link href="<?= ASSETS ?>plugins/pace/pace.min.css" rel="stylesheet" />
	<script src="<?= ASSETS ?>plugins/pace/pace.min.js"></script>
	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

	<!-- <link href="<?= ASSETS ?>plugins/bootstrap_bundle/css/bootstrap.min.css" rel="stylesheet"> -->
	<link href="<?= ASSETS ?>css/icons.css" rel="stylesheet">
	<link href="<?= ASSETS ?>css/app.css" rel="stylesheet">
	<!-- Theme Style CSS -->
	<link rel="stylesheet" href="https://unpkg.com/tippy.js@6/themes/light-border.css" />
	<title><?= is_array($data) ? $data['page_title'] : $data . " | " . APP_NAME ?></title>
</head>