<?php $this->loadView("includes/html_header",$data);?>

<body class="bg-forgot">
	<!-- wrapper -->
	<div class="wrapper">
		<div class="authentication-forgot d-flex align-items-center justify-content-center">
			<div class="card forgot-box">
				<div class="card-body">
					<div class="p-4 rounded border">
						<div class="text-center">
							<img src="<?=ASSETS?>images/icons/forgot-2.png" width="120" alt="" />
						</div>
						<h4 class="mt-5 font-weight-bold">Forgot Password?</h4>
						<p class="text-muted">Enter your registered email to reset the password.</p>
						<div class="form-body">
							<form class="" action="<?=URL_ROOT?>users/forgot_password" method="post">
								<div class="my-4">
									<label for="inputEmailAddress" class="form-label">Email Address</label>
									<input type="email" name="email" class="form-control form-control-lg <?= !empty($data['errors']['email_err']) ? 'is-invalid' : '' ?>" id="inputEmailAddress" placeholder="example@user.com" value="<?=$data['email']?>"/>
									<?php if(!empty($data['errors']['email_err'])) : ?>
										<span class="invalid-feedback"><?=$data['errors']['email_err']?></span>
									<?php endif ?>
								</div>
								<div class="d-grid gap-2">
									<button type="submit" class="btn btn-primary btn-lg">Send</button>
									<a href="<?=URL_ROOT?>users/login" class="btn btn-light btn-lg">
										<i class='bx bx-arrow-back me-1'></i>
										Back to Login
									</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end wrapper -->
</body>

</html>