		<?php $this->loadView("includes/html_header", $data['page_title']); ?>

		<body>
			<!--wrapper-->
			<div class="wrapper">
				<!--sidebar wrapper -->
				<?php $this->loadView("includes/sidebar", $data); ?>
				<!--end sidebar wrapper -->

				<!--start header -->
				<?php $this->loadView("includes/header"); ?>
				<!--end header -->
				<!--start page wrapper -->
				<div class="page-wrapper">
					<div class="page-content">
						<?= show($_SESSION) ?>
						<?php //show($data)
						?>
						<div class="row row-cols-1 row-cols-md-2 row-cols-xl-4">
							<div class="col">
								<div class="card radius-10 bg-gradient-deepblue">
									<div class="card-body">
										<div class="d-flex align-items-center">
											<h5 class="mb-0 text-white">9526</h5>
											<div class="ms-auto">
												<i class='bx bx-cart fs-3 text-white'></i>
											</div>
										</div>
										<div class="progress my-3 bg-light-transparent" style="height:3px;">
											<div class="progress-bar bg-white" role="progressbar" style="width: 55%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
										<div class="d-flex align-items-center text-white">
											<p class="mb-0">Total Orders</p>
											<p class="mb-0 ms-auto">+4.2%<span><i class='bx bx-up-arrow-alt'></i></span></p>
										</div>
									</div>
								</div>
							</div>
							<div class="col">
								<div class="card radius-10 bg-gradient-orange">
									<div class="card-body">
										<div class="d-flex align-items-center">
											<h5 class="mb-0 text-white">$8323</h5>
											<div class="ms-auto">
												<i class='bx bx-dollar fs-3 text-white'></i>
											</div>
										</div>
										<div class="progress my-3 bg-light-transparent" style="height:3px;">
											<div class="progress-bar bg-white" role="progressbar" style="width: 55%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
										<div class="d-flex align-items-center text-white">
											<p class="mb-0">Total Revenue</p>
											<p class="mb-0 ms-auto">+1.2%<span><i class='bx bx-up-arrow-alt'></i></span></p>
										</div>
									</div>
								</div>
							</div>
							<div class="col">
								<div class="card radius-10 bg-gradient-ohhappiness">
									<div class="card-body">
										<div class="d-flex align-items-center">
											<h5 class="mb-0 text-white">6200</h5>
											<div class="ms-auto">
												<i class='bx bx-group fs-3 text-white'></i>
											</div>
										</div>
										<div class="progress my-3 bg-light-transparent" style="height:3px;">
											<div class="progress-bar bg-white" role="progressbar" style="width: 55%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
										<div class="d-flex align-items-center text-white">
											<p class="mb-0">Visitors</p>
											<p class="mb-0 ms-auto">+5.2%<span><i class='bx bx-up-arrow-alt'></i></span></p>
										</div>
									</div>
								</div>
							</div>
							<div class="col">
								<div class="card radius-10 bg-gradient-ibiza">
									<div class="card-body">
										<div class="d-flex align-items-center">
											<h5 class="mb-0 text-white">5630</h5>
											<div class="ms-auto">
												<i class='bx bx-envelope fs-3 text-white'></i>
											</div>
										</div>
										<div class="progress my-3 bg-light-transparent" style="height:3px;">
											<div class="progress-bar bg-white" role="progressbar" style="width: 55%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
										<div class="d-flex align-items-center text-white">
											<p class="mb-0">Messages</p>
											<p class="mb-0 ms-auto">+2.2%<span><i class='bx bx-up-arrow-alt'></i></span></p>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!--end row-->

						<div class="row row-cols-1 row-cols-lg-3">
							<div class="col">
								<div class="card radius-10">
									<div class="card-body">
										<div class="d-flex align-items-center">
											<div class="w_chart easy-dash-chart1" data-percent="60">
												<span class="w_percent"></span>
												<canvas width="110" height="110"></canvas>
											</div>
											<div class="ms-3">
												<h6 class="mb-0">Facebook Followers</h6>
												<small class="mb-0">22.14% <i class='bx bxs-up-arrow align-middle me-1'></i>Since Last Week</small>
											</div>
											<div class="ms-auto fs-1 text-facebook"><i class='bx bxl-facebook'></i></div>
										</div>
									</div>
								</div>
							</div>
							<div class="col">
								<div class="card radius-10">
									<div class="card-body">
										<div class="d-flex align-items-center">
											<div class="w_chart easy-dash-chart2" data-percent="65">
												<span class="w_percent"></span>
											</div>
											<div class="ms-3">
												<h6 class="mb-0">Twitter Tweets</h6>
												<small class="mb-0">32.15% <i class='bx bxs-up-arrow align-middle me-1'></i>Since Last Week</small>
											</div>
											<div class="ms-auto fs-1 text-twitter"><i class='bx bxl-twitter'></i></div>
										</div>
									</div>
								</div>
							</div>
							<div class="col">
								<div class="card radius-10">
									<div class="card-body">
										<div class="d-flex align-items-center">
											<div class="w_chart easy-dash-chart3" data-percent="75">
												<span class="w_percent"></span>
											</div>
											<div class="ms-3">
												<h6 class="mb-0">Youtube Subscribers</h6>
												<small class="mb-0">58.24% <i class='bx bxs-up-arrow align-middle me-1'></i>Since Last Week</small>
											</div>
											<div class="ms-auto fs-1 text-youtube"><i class='bx bxl-youtube'></i></div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!--End Row-->
					</div>
				</div>
				<!--end page wrapper -->
				<!--start overlay-->
				<div class="overlay toggle-icon"></div>
				<!--end overlay-->
				<!--Start Back To Top Button--> <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
				<!--End Back To Top Button-->
				<?php $this->loadView("includes/footer", $data); ?>