		<?php $this->loadView("includes/html_header", $data['page_title']); ?>

		<body>
			<!--wrapper-->
			<div class="wrapper">
				<!--sidebar wrapper -->
				<?php $this->loadView("includes/sidebar", $data); ?>
				<!--end sidebar wrapper -->

				<!--start header -->
				<?php $this->loadView("includes/header"); ?>
				<!--end header -->
				<!--start page wrapper -->
				<div class="page-wrapper">
					<div class="page-content">
						<!-- view/edit task modal start -->
						<?php $this->loadView("includes/view_edit_task_modal", $data); ?>
						<!-- view/edit modal end -->
						<div class="card">
							<div class="card-body">
								<div class="table-responsive">
									<div id='calendar'></div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--end page wrapper -->
				<!--start overlay-->
				<div class="overlay toggle-icon"></div>
				<!--end overlay-->
				<!--Start Back To Top Button-->
				<a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
				<!--End Back To Top Button-->
				<?php $this->loadView("includes/footer", $data); ?>